# Generated by Django 5.2.15 on 2026-06-17 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('icon', models.CharField(default='restaurant', max_length=80)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CustomizationGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('type', models.CharField(choices=[('single', 'single'), ('multi', 'multi')], default='single', max_length=10)),
                ('required', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('category_name', models.CharField(blank=True, default='', max_length=120)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('image', models.URLField(blank=True, default='', max_length=500)),
                ('popular', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'dishes',
                'ordering': ['category__order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'menu categories',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CustomizationOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('price_delta', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('order', models.PositiveIntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='catalog.customizationgroup')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='customizationgroup',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customization', to='catalog.dish'),
        ),
        migrations.AddField(
            model_name='dish',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='catalog.menucategory'),
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('cover', models.URLField(blank=True, default='', max_length=500)),
                ('logo', models.URLField(blank=True, default='', max_length=500)),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('rating_count', models.PositiveIntegerField(default=0)),
                ('delivery_minutes', models.PositiveIntegerField(default=30)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('price_level', models.PositiveSmallIntegerField(default=1)),
                ('free_delivery', models.BooleanField(default=False)),
                ('offers', models.JSONField(blank=True, default=list)),
                ('distance_km', models.FloatField(default=0)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('address', models.CharField(blank=True, default='', max_length=255)),
                ('cuisine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurants', to='catalog.cuisine')),
                ('cuisines', models.ManyToManyField(blank=True, related_name='restaurants_m2m', to='catalog.cuisine')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='menucategory',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='catalog.restaurant'),
        ),
        migrations.AddField(
            model_name='dish',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='catalog.restaurant'),
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, default='', max_length=255)),
                ('image', models.URLField(blank=True, default='', max_length=500)),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banners', to='catalog.restaurant')),
            ],
        ),
    ]
