# Generated by Django 5.2.15 on 2026-06-18 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banner",
            name="image",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="dish",
            name="image",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="cover",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="logo",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
    ]
