# Generated by Django 5.2.15 on 2026-06-17 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('discount_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('free_delivery', models.BooleanField(default=False)),
                ('min_subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('restaurant_name', models.CharField(blank=True, default='', max_length=255)),
                ('restaurant_cover', models.URLField(blank=True, default='', max_length=500)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('preparing', 'Preparing'), ('picked_up', 'Picked up'), ('on_the_way', 'On the way'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='confirmed', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('service_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tip', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('promo_code', models.CharField(blank=True, max_length=40, null=True)),
                ('payment_method', models.CharField(default='Card', max_length=120)),
                ('scheduled_for', models.CharField(blank=True, max_length=120, null=True)),
                ('placed_at', models.DateTimeField()),
                ('eta_minutes', models.PositiveIntegerField(default=0)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='accounts.address')),
                ('restaurant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='catalog.restaurant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-placed_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_id', models.CharField(blank=True, default='', max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('image', models.URLField(blank=True, default='', max_length=500)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('selected_options', models.JSONField(blank=True, default=list)),
                ('instructions', models.CharField(blank=True, default='', max_length=255)),
                ('line_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('dish', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='catalog.dish')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courier_name', models.CharField(blank=True, default='', max_length=120)),
                ('courier_avatar', models.URLField(blank=True, default='', max_length=500)),
                ('courier_phone', models.CharField(blank=True, default='', max_length=40)),
                ('route', models.JSONField(blank=True, default=list)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tracking', to='orders.order')),
            ],
        ),
    ]
