# Generated by Django 5.2.15 on 2026-06-17 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('restaurants', models.JSONField(blank=True, default=list)),
                ('dishes', models.JSONField(blank=True, default=list)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'favorites',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('type', models.CharField(default='system', max_length=40)),
                ('title', models.CharField(max_length=200)),
                ('body', models.CharField(blank=True, default='', max_length=500)),
                ('read', models.BooleanField(default=False)),
                ('date', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
